{{- if .Values.networkPolicies.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "linkurious-entity-resolution.fullname" . }}
  labels:
    {{- include "linkurious-entity-resolution.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
    {{- include "linkurious-entity-resolution.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      {{- if .Values.networkPolicies.allowSameNamespaceIngress }}
      - podSelector: {}
      {{- end }}
      {{- if .Values.networkPolicies.allowAllNamespaceIngress }}
      - namespaceSelector: {}
      {{- end }}
      ports:
      - port: http
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: mariadb

{{- end }}
