{{- if and .Values.metrics .Values.metrics.enabled }}
{{- if .Values.metrics.serviceMonitor.enabled }}
  {{- if (not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1")) }}
    {{- if (not (.Values.metrics.disableAPICheck)) }}
      {{- fail "ERROR: You have to deploy monitoring.coreos.com/v1 first or disable prometheus" }}
    {{- end }}
  {{- end }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "linkurious-entity-resolution.fullname" . }}
  {{- with .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "linkurious-entity-resolution.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: {{ .Values.metrics.serviceMonitor.jobLabel | default .Release.Name }}
  endpoints:
    - port: metrics
      path: /{{ .Values.metrics.entryPoint }}
      {{- with .Values.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.honorTimestamps }}
      honorTimestamps: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.enableHttp2 }}
      enableHttp2: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.followRedirects }}
      followRedirects: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
{{- if .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
{{ tpl (toYaml .Values.metrics.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
{{ toYaml .Values.metrics.serviceMonitor.relabelings | indent 6 }}
{{- end }}
  {{- if .Values.metrics.serviceMonitor.namespaceSelector }}
  namespaceSelector:
{{ toYaml .Values.metrics.serviceMonitor.namespaceSelector | indent 4 -}}
  {{ else }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end }}
  selector:
    matchLabels:
      {{- if (and (.Values.metrics.service).enabled) }}
      {{- include "linkurious-entity-resolution.metricslabelselector" . | nindent 6 }}
      {{- else }}
      {{- include "linkurious-entity-resolution.selectorLabels" . | nindent 6 }}
      {{- end }}
{{- end }}
{{- end }}
